all:
  children:
    infra_core:
      hosts:
        infra-01:
          ansible_host: 10.10.10.11
    infra_minio:
      hosts:
        infra-02:
          ansible_host: 10.10.10.12
    infra_headscale:
      hosts:
        infra-03:
          ansible_host: 10.10.10.13
    app:
      hosts:
        app-01:
          ansible_host: 10.10.10.21
        app-02:
          ansible_host: 10.10.10.22
        app-03:
          ansible_host: 10.10.10.23
        app-04:
          ansible_host: 10.10.10.24
        app-05:
          ansible_host: 10.10.10.25
