---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create web root
  file:
    path: "{{ nginx_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Configure Virtual Host
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/{{ nginx_server_name }}
  notify: reload nginx

- name: Enable Virtual Host
  file:
    src: /etc/nginx/sites-available/{{ nginx_server_name }}
    dest: /etc/nginx/sites-enabled/{{ nginx_server_name }}
    state: link
  notify: reload nginx
