- name: Deploy Consul, Vault, and Nginx
  hosts: infra_core
  gather_facts: true
  roles:
    - infra_consul_vault_nginx

- name: Deploy MinIO
  hosts: infra_minio
  gather_facts: true
  roles:
    - infra_minio

- name: Deploy Headscale
  hosts: infra_headscale
  gather_facts: true
  roles:
    - infra_headscale
