# System Settings
PUID=1000
PGID=1000
TZ=Asia/Seoul

# VPN Settings (NordVPN/ProtonVPN/etc)
VPN_PROVIDER=nordvpn
VPN_TYPE=wireguard
WIREGUARD_PRIVATE_KEY=
WIREGUARD_PUBLIC_KEY=
WIREGUARD_ENDPOINT_IP=
WIREGUARD_ADDRESSES=10.5.0.2/32
OPENVPN_USER=
OPENVPN_PASSWORD=

# Port Forwarding
GLUETUN_PORT_FORWARDING=off

# qBittorrent
QBITTORRENT_WEBUI_PORT=8080

# Cloudflare
CLOUDFLARED_TOKEN=
