- name: Install base packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present
    update_cache: true

- name: Enable and start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Allow SSH service in firewalld
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    immediate: true
    state: enabled

- name: Ensure qemu guest agent is enabled
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true

- name: Ensure platform root directory exists
  ansible.builtin.file:
    path: "{{ platform_root_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure project root directory exists
  ansible.builtin.file:
    path: "{{ project_root_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
